### PR TITLE
feat: implement cache table for sorted_cache lookup

### PR DESCRIPTION
**Pull request by yogimathius**
### What was done?
**DO NOT MERGE YET**
- creates a hash_table using [the following tutorial](https://benhoyt.com/writings/hash-table-in-c/), with all use of `malloc` and `free` replaced with `mmap` and `munmap`.
- replaced `void* value` with `t_chunk* value`, TBD if this is how we may actually use it?
- putting this PR up to merge in sooner than later to begin working off this implementation with your code when ready 🙏 

### :tophat: Instructions

- CI/CD still checks out. Will add tests tomorrow, getting late 😁

### CODE REVIEW

**Comment by yogimathius** [comment]
@rswhipple we should try to roll with this version of the cache table asap so we don't have to spend too much time on the other cache_table implementation. I still need to test it out on my end but that tutorial provides a lot of methods to work with and I'm feeling optimistic about using them. 

If you're into that idea we can merge my three PRs in tomorrow (thurs, Jun 6 😁) and I can continue testing it tomorrow night 🙏 

I understand there's a bit more that needs to be considered for the `cache_table_get` method to properly find what we want, with our data structure, and will see what I can come to with it by tomorrow night :)

**Comment by yogimathius** [comment]
you'll also see I think [this](https://github.com/rswhipple/jsmalloc/pull/41/files#diff-0a1ea1f030ae0e4b09926b22a6169314c8a32f958ee4dfd59ddac0f5d52cf782R39) might be what we wanted so the end of the cache is later in memory than where the sorted_cache table ends?

**Comment by yogimathius** [comment]
also if you prefer to keep the extra logs running lmk and I'll uncomment ;)

**Review by rswhipple — APPROVED** [review]
looks good, happy to go with your hash_table implementation

**Pull request merged**
